### ISSUE TITLE
Add new device support Neo NAS-AB02B0 (Alarm, temp&hum sensor)

### ISSUE THREAD

**Issue by borodamd** [slsys/Gateway#100]
Hi. Try to add support for this device. It's very helpful device.

![z2m](https://user-images.githubusercontent.com/8099685/109027166-2e2ae800-76c9-11eb-9298-6173160128f8.png)
![z2m-2](https://user-images.githubusercontent.com/8099685/109027523-8e218e80-76c9-11eb-8ca3-5cf4eef556e7.png)

[zigbee2mqtt page](https://www.zigbee2mqtt.io/devices/NAS-AB02B0.html)

[zigbee2mqtt pairing log](https://pastebin.com/nXF20zfg)

[sls pairing log](https://pastebin.com/FvvsVqB4)

sls device page:
![sls](https://user-images.githubusercontent.com/8099685/109027535-924dac00-76c9-11eb-9d8f-026e3b65ae6c.png)

**Comment by Avenitos** [comment]
already added in 2020.02.xx :)

**Comment by maxxpda** [comment]
Данное устройство джойнится,но не отправляет все данные: нет температуры,влажности,тревоги и прочее
![Снимок экрана 2021-12-02 в 23 08 51](https://user-images.githubusercontent.com/87569708/144958353-aa763633-7950-4c24-adcc-cf67a6e0a1a9.png)
.
