### ISSUE TITLE
Add new device support: _TZ3000_ TS0001 (Tuya Zigbee mini switch)

### ISSUE THREAD

**Issue by morphygee** [slsys/Gateway#112]
Device Info:

![SLS Gateway: Zigbee device #0x86C2 2021-05-21 08-41-28](https://user-images.githubusercontent.com/18217647/119094090-d9b9af00-ba10-11eb-8db9-aae1754a16bd.jpg)

Pairing log:

> [08:22:45.113] [V] AREQ_ZDO_TC_DEV_IND SrcNwkAddr: 0x86C2, SrcIEEEAddr: 0x847127FFFE0A9679, ParentNwkAddr: 0x0000
> [08:22:48.057] [V] AREQ_ZDO_TC_DEV_IND SrcNwkAddr: 0x86C2, SrcIEEEAddr: 0x847127FFFE0A9679, ParentNwkAddr: 0x0000
> [08:22:51.421] [V] AREQ_ZDO_TC_DEV_IND SrcNwkAddr: 0x86C2, SrcIEEEAddr: 0x847127FFFE0A9679, ParentNwkAddr: 0x0000
> [08:22:51.476] [V] AREQ_ZDO_END_DEVICE_ANNCE_IND SrcNwkAddr: 0x86C2, NwkAddr: 0x86C2, ieeeAddr: 0x847127FFFE0A9679, Capabilites: 0x8E
> [08:22:51.481] Device announce: 0x847127FFFE0A9679, DevType: Router, PowerSource: Main, ReceiverOnIdle: ON, Security: OFF
> [08:22:52.065] [V]  -- Found active Endpoints, nwkAddr: 0x86C2, Endpoints: 1,242
> [08:22:52.190] NumInClusters: 0
> [08:22:52.195] NumOutClusters: 1
> [08:22:52.319] NumInClusters: 7
> [08:22:52.326] NumOutClusters: 2
> [08:22:52.449] [V] AREQ_AF_INCOMING_MSG GroupId: 0x0000, ClusterId: 0x0000 GEN_BASIC, SrcAddr: 0x86C2, SrcEn: 1, DstEn: 1, WasBr: 0x00, LinkQuality: 141, SecurityUse: 0x00, TimeStamp: 0x00563A0D, TransSeqNum: 0, Len: 40, Data: 18180104000042105F545A333030305F686B74716168727105000042065453303030310700003001
> [08:22:52.473] [V]   ZCL FrameControl: 0x18, Type: 00, ManuSpecific: 00, Direction: 01, DisableDefaultRsp: 01, TrSeqNum: 24, CmdId: 0x01 READ_RSP, Payload: 04000042105F545A333030305F686B74716168727105000042065453303030310700003001
> [08:22:52.504] [V]     AttrId: 0x0004, AttrDataType: 0x42, AttrDataLen: 17, AttrValue: _TZ3000_hktqahrq
> [08:22:52.511] [V]     AttrId: 0x0005, AttrDataType: 0x42, AttrDataLen: 7, AttrValue: TS0001
> [08:22:52.515] [V]     AttrId: 0x0007, AttrDataType: 0x30, AttrDataLen: 1, AttrValue: 1
> [08:22:52.534] New device 'TS0001' with address 0x847127FFFE0A9679 interview completed!
> [08:22:52.554] [ERROR] Device: 0x847127FFFE0A9679 converter FromZigbee not found for CID: 0, ManufName: _TZ3000_hktqahrq, ModelId: TS0001
> [08:22:55.154] Device with address 0x86C2 configuration starting...
> [08:22:55.172] SaveDevices()
> [08:22:55.233] 3 311544 164832 91696
> [08:22:55.238] FreeMem: 162976
> [08:22:55.243] JsonSize: 3066
> [08:22:55.515] FileWrite time: 338
> [08:22:55.530] free2
> [08:22:55.535] free2 done

Device Image:

![SMATRUL Tuya ZigBee Smart Light Switch Module 16A Mini Automation DIY Breaker 2 Way Timing Control For Alexa Google Home Gatewa… 2021-05-21 08-40-40](https://user-images.githubusercontent.com/18217647/119094325-2d2bfd00-ba11-11eb-8d71-2f0eff4db957.jpg)

**Comment by Avenitos** [comment]
[Updated in SLS firmware: 2021.07.05d3](https://github.com/slsys/Gateway/blob/master/devices/Zigbee/41/readme.md)
