### ISSUE TITLE
Локальное время в скриптах LUA

### ISSUE THREAD

**Issue by georotor** [slsys/Gateway#169]
Сейчас у нас есть возможность получить время в скрипте через `os.time()`, при этом возвращается unix тайм без учета тайм зоны, хотя в веб интерфейсе она указана. Из-за этого в скриптах приходится повторно её прописывать (переменная или объект). Было бы здорово иметь что то вроде `os.timeLocal()` возвращающее уже локальное время.

**Comment by tsurkan-av** [comment]
При обработке скриптов доступны события Event.Time. В событиях время с учетом timezone. Если используется os.time() то так или иначе оно обрабатывается для выделения часов/минут/etc, поэтому здесь не составляет труда добавить timezone
