### ISSUE TITLE
Add MQTT auto discovery for Home Assistant

### ISSUE THREAD

**Issue by schmurtzm** [slsys/Gateway#18]
Could be great to add MQTT auto discovery for Home Assistant.
https://home-assistant.io/docs/mqtt/discovery/

More and more automation systems are able to use the auto-discovery feature with MQTT broker (so basically you don't need to declare one by one all your sensors, switches,... in your automation system, they are automatically created with correct type first time your device is going to connect to the MQTT broker of your system).

So here is the cooking book for it ;)

- you need to setup the root prefix for autodiscovery (should be a field to fill). For Home Assistant it's homeassistant basically. That field should be combined with a button to "activate" the discovery and a unique node ID (user filable).

- Once discovery button has been pushed and device restarted, it'll send automatically on MQTT broker setup in SLS Gateway a configuration topic for each hardware device configured in SLS Gateway. 
The configuration topic should be formatted this way:
`<discovery_prefix>/<component>/[<node_id>/]<object_id>/config`

   - **"component"** being one of the type previously listed

   - **"node_id"** being an optional field to supply node providing the topic
   - **"object_id"** being the unique node ID filled by user in SLS Gateway parameters (if not filled can be by default the last digits of the MAC address of the zigbee device for example)
   - **"\<\>"** being the config or state to define current action.

For more details with Home assistant (basically same process with all MQTT clients that support auto-discovery): https://home-assistant.io/docs/mqtt/discovery/

If you need a tester, I'm your man :)

**Comment by papperone** [comment]
I do agree this shoudl be a "must" features that will make me drop the zigbee2mqtt integration and move all to an SLSGateway! 
If you need additional tester count me in!!

**Comment by kukudemajia** [comment]
If you need additional tester count me in!!

**Comment by Avenitos** [comment]
Большая часть устройств должна пробрасывать в MQTT
