### ISSUE TITLE
Добавить поддержку WXCJKG13LM (Xiaomi Aqara Opple switch 3 bands (action)

### ISSUE THREAD

**Issue by directman66** [slsys/Gateway#2]
blob:https://web.telegram.org/40e757cd-efe6-4ac0-a7ad-04a20a41a583

blob:https://web.telegram.org/afebe9e2-0b06-4a4b-a01a-14c81ead1db4

**Comment by directman66** [comment]
Не проходит интервью. Нужно снифить

**Comment by directman66** [comment]
https://pastebin.com/wMdH2yxa

**Comment by directman66** [comment]
тест

**Comment by Avenitos** [comment]
Поддержка добавлена в 20200127
