### ISSUE TITLE
Отсутствует конвертер для ламп IKEA TRADFRI bulb E27 WS clear 950lm LED1546G12

### ISSUE THREAD

**Issue by EagleAlex** [slsys/Gateway#27]
Отсутствует конвертер для ламп IKEA TRADFRI bulb E27 WS clear 950lm LED1546G12.
Прошивка: 20.20.05.12b.
Zigbee: CC2538 + MODKAMRU_V3_UART-no-flow-control_20200211

**Comment by Avenitos** [comment]
Добавлено в версии 2020.06.22d3
