### ISSUE TITLE
Add feature - enable MQTT retain for single device

### ISSUE THREAD

**Issue by snakuzzo** [slsys/Gateway#29]
Hi all!
it may be useful to have an option to enable MQTT retain for each device 

This would be very useful in the case of deep sleep sensors (eg. Aqara doors and windows sensors).
If hub (e.g. homeassistant) restarts and state topic was not retained, the state is wrong until next state change or until next publish and...IMHO...it's wrong to enable MQTT retain for every MQTT messages of every device .

Thanks

**Comment by papperone** [comment]
I do agree to have selective retain per device will be a great addition for the SLS firmware!

**Comment by snakuzzo** [comment]
Any news about this feature ?

**Comment by Avenitos** [comment]
Lua: zigbee.setretain(Ident)
