### ISSUE TITLE
Link quality is always 0 for SONOFF BASICZBR3

### ISSUE THREAD

**Issue by malesci** [slsys/Gateway#33]
Hello,
I'm on Version: 2020.07.24d1 on-board on a 16Mb device.

SLS Info
Version: 2020.07.24d1
Zigbee devices: 12
Uptime: 00:06:31
LastSave: 00:06:20
FreeHeap: 177852 bytes
FreeHeapCommon: 4329988 bytes
TotalPsram: 4194252 bytes
FreePsram: 4194252 bytes
FirmwareSize: 1631200 bytes
Flash: 16Mb QOUT 80

After joining a device Manuf: SONOFF ModelId: BASICZBR3, there are no values for linkquality property.
This device is also a router and all the end-device connected to it, have no values for linkquality property as well.

thank you

**Comment by Avenitos** [comment]
Link quality is displayed as the device sent
