### ISSUE TITLE
Добавить поддержку Philips Hue Outdoor Sensor

### ISSUE THREAD

**Issue by Alex18081** [slsys/Gateway#5]
![photo_2020-02-11_21-24-26](https://user-images.githubusercontent.com/20165670/74275898-04e52700-4d15-11ea-8495-cfaec23bd69c.jpg)
![photo_2020-02-11_21-24-03](https://user-images.githubusercontent.com/20165670/74275918-0f072580-4d15-11ea-91f3-74f2a190a5aa.jpg)
![photo_2020-02-11_21-24-20](https://user-images.githubusercontent.com/20165670/74275929-11697f80-4d15-11ea-8a1d-e5231ca777f5.jpg)

**Comment by Avenitos** [comment]
Добавлено в 20200227
