### ISSUE TITLE
Feature request: basic HTTP authentication

### ISSUE THREAD

**Issue by kolobus** [slsys/Gateway#54]
Очень нужна хотя бы самая простая аутентификация, а то совсем беда.
Делается очень легко, двумя http-заголовками.

- Значение пароля задается в админке или в отдельном файле.
- В режиме AP пароль сбрасывается, иначе забытый пароль будет не восстановить.

**Comment by Avenitos** [comment]
Добавлена полноценная аутентификация в версии 2021.04.01d5
