### ISSUE TITLE
Добавить поддержку IKEA Shortcut

### ISSUE THREAD

**Issue by DjBalagur** [slsys/Gateway#6]
![CCAC572A-F1CF-4411-882E-DD6A0E70E0D5](https://user-images.githubusercontent.com/7229740/74301161-371d7580-4d63-11ea-8803-6da7203f4120.png)
![8999207D-3CCB-4A3F-BCE5-0F05B650B886](https://user-images.githubusercontent.com/7229740/74301201-5a482500-4d63-11ea-8cbd-8219140c6215.png)

**Comment by DjBalagur** [comment]
`ieeeAddr = 680AE2FFFE2F39CC
last_seen = 1581355384
type = EndDevice
powerSource = Battery
Interview = {"TS":0,"State":4}
ep 1
-- profId = 260
-- In
-- -- 0x0000 GEN_BASIC
-- -- 0x0001 GEN_POWER_CFG
-- -- 0x0003 GEN_IDENTIFY
-- -- 0x0009 GEN_ALARMS
-- -- 0x0020 GEN_POLL_CONTROL
-- -- 0x1000 LIGHT_LINK
-- Out
-- -- 0x0003 GEN_IDENTIFY
-- -- 0x0004 GEN_GROUPS
-- -- 0x0006 GEN_ON_OFF
-- -- 0x0008 GEN_LEVEL_CONTROL
-- -- 0x0019 OTA
-- -- 0x0102 CLOSURES_WINDOW_COVERING
-- -- 0x1000 LIGHT_LINK
-- devId = 2080
Rcf = true
ManufName = IKEA of Sweden
ModelId = TRADFRI SHORTCUT Button
st = {"linkquality":63,"trSeqNum":0}
supported = 2
friendly_name = IKEA Shortcut `

**Comment by Avenitos** [comment]
Добавлено в 20200227
