### ISSUE TITLE
Gateway is resetting on receiving MQTT message for Xiaomi relay

### ISSUE THREAD

**Issue by marsal87** [slsys/Gateway#8]
If you send a MQTT message for relay (MiGateway/0x00158D0003CB8DEE/set/state_l1/) the watchdog is triggered. It occures first about 6 minutes after gateway started. Other binded devices work fine.
The configuration with the same hardware, but without ESP32 was tested with zigbee2mqtt and it works.

Here are the logs:
[192.168.188.57-20200212-212116.log](https://github.com/slsys/Gateway/files/4209618/192.168.188.57-20200212-212116.log)
[192.168.188.57-20200211-190633.log](https://github.com/slsys/Gateway/files/4209619/192.168.188.57-20200211-190633.log)

Configuration:
- ESP32 Firmware version: 20200202
- Gateway from Jager with CC2538+CC2592
- CC2538 firmware:
           MODKAMRU_V3_UART-no-flow-control
           CC2538ZNP-UART-without-SBL-cc2592
          (tried both)
- Relay LLKZMK11LM

**Comment by avdeevsv91** [comment]
У меня проблема не воспроизводится, железо тоже самое, прошивка последняя.
