### ISSUE TITLE
TRÅDFRI shortcut button repeats same command 4 times

### ISSUE THREAD

**Issue by ifujis** [slsys/Gateway#88]
TRÅDFRI shortcut button (v.2.3.015) sends the same command four times for a single action. The trSeqNum is the same for all four repetitions.
It causes a toggle action to be executed 4 times in SimpleBind which makes it useless.

Web log: https://pastebin.com/GWwFLjjy

As possible solution, add a check for trSeqNum to ignore subsequent commands with the same trSeqNum.

**Comment by Avenitos** [comment]
this will be fixed in the new version 2021.01.24d1
