### ISSUE TITLE
Wrong device class for DIYRuZ_Flower's soil moisture sensor sents to MQTT topic

### ISSUE THREAD

**Issue by litichevskiydv** [slsys/Gateway#89]
Gateway sents to topic `homeassistant/sensor/<sensor_address>/soil_moisture/config` message with device class `moisture`
```
{
  "device_class": "moisture",
  "unit_of_measurement": "%",
  "value_template": "{{ value_json.soil_moisture }}",
  ....
}.
```
But according to [documentation](https://www.home-assistant.io/integrations/sensor/) such device class is not supported for sensors, so Home Assistant can not automatically create entity for sensor.

**Comment by Avenitos** [comment]
Thanks! I fixed this
