### ISSUE TITLE
Add new device support - Philips Hue Lightstrip Plus (929002269110)

### ISSUE THREAD

**Issue by limorenko** [slsys/Gateway#90]
**Philips Hue Lightstrip Plus (Product Code: 929002269110)**

SLS Version: 2020.12.16d1
Device 0x0017880108D65293

Successfully joined!
Current status: Power source received
New nwkAddr: 0x99AC
ParentnwkAddr: 0x0000
Type: Router
Endpoint #11: ProfileId=260 DeviceId=269
Endpoint #242: ProfileId=41440 DeviceId=97
ManufName: Philips
Model: LCL001
Power source: Mains (single phase)

**Pairing log**: https://pastebin.com/PjxhdQic

**Device info:**
**Router**
**ieeeAddr**: 0x0017880108D65293
**nwkAddr**: 0x99AC
**Power source**: Mains (single phase)
**ManufName**: Philips
**ModelId**: LCL001
**Routes**
**Endpoint #11**
ProfileId: 0x0104
DeviceId: 0x010D
Input clusters:
`GEN_BASIC`
`GEN_IDENTIFY`
`GEN_GROUPS`
`GEN_SCENES`
`GEN_ON_OFF`
`GEN_LEVEL_CONTROL`
`LIGHTING_COLOR_CONTROL`
`TOUCHLINK`
Output clusters: `OTA`
**Endpoint #242**
ProfileId: 0xA1E0
DeviceId: 0x0061
Input clusters: `None`
Output clusters: `GREEN_POWER_PROXY`

![LCL001](https://user-images.githubusercontent.com/11735443/104091875-5d100a80-5291-11eb-83bb-f5d1cde1ef1c.png)

**Comment by limorenko** [comment]
![LCL001_128x128](https://user-images.githubusercontent.com/11735443/105667668-c710ec80-5eec-11eb-83b1-9a764e94227a.png)

**Comment by limorenko** [comment]
https://www.zigbee2mqtt.io/devices/8718699703424.html

**Comment by Avenitos** [comment]
добавлено с версии 2021.02.02d2
